### ISSUE TITLE
Install Sentry.io

### ISSUE THREAD

**Issue by blt950** [Vatsim-Scandinavia/handover#49]
Because it's nice to know if things to go hell

**Comment by blt950** [comment]
Still some issue that it doesn't send the message. Either it's the sentry or missing php-extension?

```There was an error sending the event.
SDK: Failed to send the event to Sentry. Reason: "Call to undefined function Symfony\Component\HttpClient\curl_multi_exec()".
Please check the error message from the SDK above for further hints about what went wrong.
PHP Fatal error:  Uncaught Error: Call to undefined function Symfony\Component\HttpClient\curl_multi_exec() in /var/www/html/vendor/symfony/http-client/CurlHttpClient.php:325
Stack trace:
#0 /var/www/html/vendor/symfony/http-client/Internal/HttplugWaitLoop.php(65): Symfony\Component\HttpClient\CurlHttpClient->stream()
#1 /var/www/html/vendor/symfony/http-client/HttplugClient.php(148): Symfony\Component\HttpClient\Internal\HttplugWaitLoop->wait()
#2 /var/www/html/vendor/symfony/http-client/HttplugClient.php(238): Symfony\Component\HttpClient\HttplugClient->wait()
#3 [internal function]: Symfony\Component\HttpClient\HttplugClient->__destruct()
#4 {main}
  thrown in /var/www/html/vendor/symfony/http-client/CurlHttpClient.php on line 325```
